name: connectivity_plus_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  share_plus: ^7.1.0
  path_provider: ^2.1.1
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
